# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tax_api import TaxApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaxApi(unittest.TestCase):
    """TaxApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tax_api.TaxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tax_class_info(self):
        """Test case for tax_class_info

        """
        pass


if __name__ == '__main__':
    unittest.main()
