# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20076 import InlineResponse20076  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20076(unittest.TestCase):
    """InlineResponse20076 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20076(self):
        """Test InlineResponse20076"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20076.InlineResponse20076()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
