# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_review import ProductReview  # noqa: E501
from swagger_client.rest import ApiException


class TestProductReview(unittest.TestCase):
    """ProductReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductReview(self):
        """Test ProductReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_review.ProductReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
