# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20031 import InlineResponse20031  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20031(unittest.TestCase):
    """InlineResponse20031 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20031(self):
        """Test InlineResponse20031"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20031.InlineResponse20031()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
