# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20059 import InlineResponse20059  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20059(unittest.TestCase):
    """InlineResponse20059 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20059(self):
        """Test InlineResponse20059"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20059.InlineResponse20059()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
