# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_add_group_prices import ProductAddGroupPrices  # noqa: E501
from swagger_client.rest import ApiException


class TestProductAddGroupPrices(unittest.TestCase):
    """ProductAddGroupPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductAddGroupPrices(self):
        """Test ProductAddGroupPrices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_add_group_prices.ProductAddGroupPrices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
