# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.webhook_api import WebhookApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhookApi(unittest.TestCase):
    """WebhookApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.webhook_api.WebhookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhook_count(self):
        """Test case for webhook_count

        """
        pass

    def test_webhook_create(self):
        """Test case for webhook_create

        """
        pass

    def test_webhook_delete(self):
        """Test case for webhook_delete

        """
        pass

    def test_webhook_events(self):
        """Test case for webhook_events

        """
        pass

    def test_webhook_list(self):
        """Test case for webhook_list

        """
        pass

    def test_webhook_update(self):
        """Test case for webhook_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
