# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_response_cart_script_list import ModelResponseCartScriptList  # noqa: E501
from swagger_client.rest import ApiException


class TestModelResponseCartScriptList(unittest.TestCase):
    """ModelResponseCartScriptList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelResponseCartScriptList(self):
        """Test ModelResponseCartScriptList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_response_cart_script_list.ModelResponseCartScriptList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
