# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subscriber_api import SubscriberApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriberApi(unittest.TestCase):
    """SubscriberApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.subscriber_api.SubscriberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subscriber_list(self):
        """Test case for subscriber_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
