# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_api import ProductApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.product_api.ProductApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_product_add(self):
        """Test case for product_add

        """
        pass

    def test_product_attribute_list(self):
        """Test case for product_attribute_list

        """
        pass

    def test_product_attribute_value_set(self):
        """Test case for product_attribute_value_set

        """
        pass

    def test_product_attribute_value_unset(self):
        """Test case for product_attribute_value_unset

        """
        pass

    def test_product_brand_list(self):
        """Test case for product_brand_list

        """
        pass

    def test_product_child_item_find(self):
        """Test case for product_child_item_find

        """
        pass

    def test_product_child_item_info(self):
        """Test case for product_child_item_info

        """
        pass

    def test_product_child_item_list(self):
        """Test case for product_child_item_list

        """
        pass

    def test_product_count(self):
        """Test case for product_count

        """
        pass

    def test_product_currency_add(self):
        """Test case for product_currency_add

        """
        pass

    def test_product_currency_list(self):
        """Test case for product_currency_list

        """
        pass

    def test_product_delete(self):
        """Test case for product_delete

        """
        pass

    def test_product_fields(self):
        """Test case for product_fields

        """
        pass

    def test_product_find(self):
        """Test case for product_find

        """
        pass

    def test_product_image_add(self):
        """Test case for product_image_add

        """
        pass

    def test_product_image_delete(self):
        """Test case for product_image_delete

        """
        pass

    def test_product_image_update(self):
        """Test case for product_image_update

        """
        pass

    def test_product_info(self):
        """Test case for product_info

        """
        pass

    def test_product_list(self):
        """Test case for product_list

        """
        pass

    def test_product_manufacturer_add(self):
        """Test case for product_manufacturer_add

        """
        pass

    def test_product_option_add(self):
        """Test case for product_option_add

        """
        pass

    def test_product_option_assign(self):
        """Test case for product_option_assign

        """
        pass

    def test_product_option_list(self):
        """Test case for product_option_list

        """
        pass

    def test_product_option_value_add(self):
        """Test case for product_option_value_add

        """
        pass

    def test_product_option_value_assign(self):
        """Test case for product_option_value_assign

        """
        pass

    def test_product_option_value_update(self):
        """Test case for product_option_value_update

        """
        pass

    def test_product_price_add(self):
        """Test case for product_price_add

        """
        pass

    def test_product_price_delete(self):
        """Test case for product_price_delete

        """
        pass

    def test_product_price_update(self):
        """Test case for product_price_update

        """
        pass

    def test_product_review_list(self):
        """Test case for product_review_list

        """
        pass

    def test_product_store_assign(self):
        """Test case for product_store_assign

        """
        pass

    def test_product_tax_add(self):
        """Test case for product_tax_add

        """
        pass

    def test_product_update(self):
        """Test case for product_update

        """
        pass

    def test_product_variant_add(self):
        """Test case for product_variant_add

        """
        pass

    def test_product_variant_count(self):
        """Test case for product_variant_count

        """
        pass

    def test_product_variant_delete(self):
        """Test case for product_variant_delete

        """
        pass

    def test_product_variant_image_add(self):
        """Test case for product_variant_image_add

        """
        pass

    def test_product_variant_info(self):
        """Test case for product_variant_info

        """
        pass

    def test_product_variant_list(self):
        """Test case for product_variant_list

        """
        pass

    def test_product_variant_price_add(self):
        """Test case for product_variant_price_add

        """
        pass

    def test_product_variant_price_delete(self):
        """Test case for product_variant_price_delete

        """
        pass

    def test_product_variant_price_update(self):
        """Test case for product_variant_price_update

        """
        pass

    def test_product_variant_update(self):
        """Test case for product_variant_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
