# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.catalog_price_rule import CatalogPriceRule  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogPriceRule(unittest.TestCase):
    """CatalogPriceRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogPriceRule(self):
        """Test CatalogPriceRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.catalog_price_rule.CatalogPriceRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
