# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_response_order_shipment_list import ModelResponseOrderShipmentList  # noqa: E501
from swagger_client.rest import ApiException


class TestModelResponseOrderShipmentList(unittest.TestCase):
    """ModelResponseOrderShipmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelResponseOrderShipmentList(self):
        """Test ModelResponseOrderShipmentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_response_order_shipment_list.ModelResponseOrderShipmentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
