# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_cart_add(self):
        """Test case for account_cart_add

        """
        pass

    def test_account_cart_list(self):
        """Test case for account_cart_list

        """
        pass

    def test_account_config_update(self):
        """Test case for account_config_update

        """
        pass

    def test_account_failed_webhooks(self):
        """Test case for account_failed_webhooks

        """
        pass

    def test_account_supported_platforms(self):
        """Test case for account_supported_platforms

        """
        pass


if __name__ == '__main__':
    unittest.main()
