# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_api import CustomerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.customer_api.CustomerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_customer_add(self):
        """Test case for customer_add

        """
        pass

    def test_customer_attribute_list(self):
        """Test case for customer_attribute_list

        """
        pass

    def test_customer_count(self):
        """Test case for customer_count

        """
        pass

    def test_customer_find(self):
        """Test case for customer_find

        """
        pass

    def test_customer_group_add(self):
        """Test case for customer_group_add

        """
        pass

    def test_customer_group_list(self):
        """Test case for customer_group_list

        """
        pass

    def test_customer_info(self):
        """Test case for customer_info

        """
        pass

    def test_customer_list(self):
        """Test case for customer_list

        """
        pass

    def test_customer_update(self):
        """Test case for customer_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
