# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.category_api import CategoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoryApi(unittest.TestCase):
    """CategoryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.category_api.CategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_category_add(self):
        """Test case for category_add

        """
        pass

    def test_category_assign(self):
        """Test case for category_assign

        """
        pass

    def test_category_count(self):
        """Test case for category_count

        """
        pass

    def test_category_delete(self):
        """Test case for category_delete

        """
        pass

    def test_category_find(self):
        """Test case for category_find

        """
        pass

    def test_category_image_add(self):
        """Test case for category_image_add

        """
        pass

    def test_category_image_delete(self):
        """Test case for category_image_delete

        """
        pass

    def test_category_info(self):
        """Test case for category_info

        """
        pass

    def test_category_list(self):
        """Test case for category_list

        """
        pass

    def test_category_unassign(self):
        """Test case for category_unassign

        """
        pass

    def test_category_update(self):
        """Test case for category_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
