# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attribute_api import AttributeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributeApi(unittest.TestCase):
    """AttributeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.attribute_api.AttributeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attribute_add(self):
        """Test case for attribute_add

        """
        pass

    def test_attribute_assign_group(self):
        """Test case for attribute_assign_group

        """
        pass

    def test_attribute_assign_set(self):
        """Test case for attribute_assign_set

        """
        pass

    def test_attribute_attributeset_list(self):
        """Test case for attribute_attributeset_list

        """
        pass

    def test_attribute_count(self):
        """Test case for attribute_count

        """
        pass

    def test_attribute_delete(self):
        """Test case for attribute_delete

        """
        pass

    def test_attribute_group_list(self):
        """Test case for attribute_group_list

        """
        pass

    def test_attribute_info(self):
        """Test case for attribute_info

        """
        pass

    def test_attribute_list(self):
        """Test case for attribute_list

        """
        pass

    def test_attribute_type_list(self):
        """Test case for attribute_type_list

        """
        pass

    def test_attribute_unassign_group(self):
        """Test case for attribute_unassign_group

        """
        pass

    def test_attribute_unassign_set(self):
        """Test case for attribute_unassign_set

        """
        pass

    def test_attribute_update(self):
        """Test case for attribute_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
