# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BasketLiveShippingService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'callback': 'str',
        'callback_err_cnt': 'int',
        'enabled_on_store': 'bool',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'callback': 'callback',
        'callback_err_cnt': 'callback_err_cnt',
        'enabled_on_store': 'enabled_on_store',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, name=None, callback=None, callback_err_cnt=None, enabled_on_store=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """BasketLiveShippingService - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._callback = None
        self._callback_err_cnt = None
        self._enabled_on_store = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if callback is not None:
            self.callback = callback
        if callback_err_cnt is not None:
            self.callback_err_cnt = callback_err_cnt
        if enabled_on_store is not None:
            self.enabled_on_store = enabled_on_store
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this BasketLiveShippingService.  # noqa: E501


        :return: The id of this BasketLiveShippingService.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BasketLiveShippingService.


        :param id: The id of this BasketLiveShippingService.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this BasketLiveShippingService.  # noqa: E501


        :return: The name of this BasketLiveShippingService.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BasketLiveShippingService.


        :param name: The name of this BasketLiveShippingService.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def callback(self):
        """Gets the callback of this BasketLiveShippingService.  # noqa: E501


        :return: The callback of this BasketLiveShippingService.  # noqa: E501
        :rtype: str
        """
        return self._callback

    @callback.setter
    def callback(self, callback):
        """Sets the callback of this BasketLiveShippingService.


        :param callback: The callback of this BasketLiveShippingService.  # noqa: E501
        :type: str
        """

        self._callback = callback

    @property
    def callback_err_cnt(self):
        """Gets the callback_err_cnt of this BasketLiveShippingService.  # noqa: E501


        :return: The callback_err_cnt of this BasketLiveShippingService.  # noqa: E501
        :rtype: int
        """
        return self._callback_err_cnt

    @callback_err_cnt.setter
    def callback_err_cnt(self, callback_err_cnt):
        """Sets the callback_err_cnt of this BasketLiveShippingService.


        :param callback_err_cnt: The callback_err_cnt of this BasketLiveShippingService.  # noqa: E501
        :type: int
        """

        self._callback_err_cnt = callback_err_cnt

    @property
    def enabled_on_store(self):
        """Gets the enabled_on_store of this BasketLiveShippingService.  # noqa: E501


        :return: The enabled_on_store of this BasketLiveShippingService.  # noqa: E501
        :rtype: bool
        """
        return self._enabled_on_store

    @enabled_on_store.setter
    def enabled_on_store(self, enabled_on_store):
        """Sets the enabled_on_store of this BasketLiveShippingService.


        :param enabled_on_store: The enabled_on_store of this BasketLiveShippingService.  # noqa: E501
        :type: bool
        """

        self._enabled_on_store = enabled_on_store

    @property
    def additional_fields(self):
        """Gets the additional_fields of this BasketLiveShippingService.  # noqa: E501


        :return: The additional_fields of this BasketLiveShippingService.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this BasketLiveShippingService.


        :param additional_fields: The additional_fields of this BasketLiveShippingService.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this BasketLiveShippingService.  # noqa: E501


        :return: The custom_fields of this BasketLiveShippingService.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this BasketLiveShippingService.


        :param custom_fields: The custom_fields of this BasketLiveShippingService.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BasketLiveShippingService, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BasketLiveShippingService):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
