# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CartWarehouse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'avail': 'bool',
        'address': 'CustomerAddress',
        'carriers_ids': 'list[str]',
        'stores_ids': 'list[str]',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'avail': 'avail',
        'address': 'address',
        'carriers_ids': 'carriers_ids',
        'stores_ids': 'stores_ids',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, name=None, description=None, avail=None, address=None, carriers_ids=None, stores_ids=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """CartWarehouse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._description = None
        self._avail = None
        self._address = None
        self._carriers_ids = None
        self._stores_ids = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if avail is not None:
            self.avail = avail
        if address is not None:
            self.address = address
        if carriers_ids is not None:
            self.carriers_ids = carriers_ids
        if stores_ids is not None:
            self.stores_ids = stores_ids
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this CartWarehouse.  # noqa: E501


        :return: The id of this CartWarehouse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CartWarehouse.


        :param id: The id of this CartWarehouse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CartWarehouse.  # noqa: E501


        :return: The name of this CartWarehouse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CartWarehouse.


        :param name: The name of this CartWarehouse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this CartWarehouse.  # noqa: E501


        :return: The description of this CartWarehouse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CartWarehouse.


        :param description: The description of this CartWarehouse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def avail(self):
        """Gets the avail of this CartWarehouse.  # noqa: E501


        :return: The avail of this CartWarehouse.  # noqa: E501
        :rtype: bool
        """
        return self._avail

    @avail.setter
    def avail(self, avail):
        """Sets the avail of this CartWarehouse.


        :param avail: The avail of this CartWarehouse.  # noqa: E501
        :type: bool
        """

        self._avail = avail

    @property
    def address(self):
        """Gets the address of this CartWarehouse.  # noqa: E501


        :return: The address of this CartWarehouse.  # noqa: E501
        :rtype: CustomerAddress
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CartWarehouse.


        :param address: The address of this CartWarehouse.  # noqa: E501
        :type: CustomerAddress
        """

        self._address = address

    @property
    def carriers_ids(self):
        """Gets the carriers_ids of this CartWarehouse.  # noqa: E501


        :return: The carriers_ids of this CartWarehouse.  # noqa: E501
        :rtype: list[str]
        """
        return self._carriers_ids

    @carriers_ids.setter
    def carriers_ids(self, carriers_ids):
        """Sets the carriers_ids of this CartWarehouse.


        :param carriers_ids: The carriers_ids of this CartWarehouse.  # noqa: E501
        :type: list[str]
        """

        self._carriers_ids = carriers_ids

    @property
    def stores_ids(self):
        """Gets the stores_ids of this CartWarehouse.  # noqa: E501


        :return: The stores_ids of this CartWarehouse.  # noqa: E501
        :rtype: list[str]
        """
        return self._stores_ids

    @stores_ids.setter
    def stores_ids(self, stores_ids):
        """Sets the stores_ids of this CartWarehouse.


        :param stores_ids: The stores_ids of this CartWarehouse.  # noqa: E501
        :type: list[str]
        """

        self._stores_ids = stores_ids

    @property
    def additional_fields(self):
        """Gets the additional_fields of this CartWarehouse.  # noqa: E501


        :return: The additional_fields of this CartWarehouse.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this CartWarehouse.


        :param additional_fields: The additional_fields of this CartWarehouse.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this CartWarehouse.  # noqa: E501


        :return: The custom_fields of this CartWarehouse.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this CartWarehouse.


        :param custom_fields: The custom_fields of this CartWarehouse.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CartWarehouse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CartWarehouse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
