# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_id': 'str',
        'order_product_id': 'str',
        'model': 'str',
        'name': 'str',
        'price': 'float',
        'price_inc_tax': 'float',
        'quantity': 'float',
        'discount_amount': 'float',
        'total_price': 'float',
        'tax_percent': 'float',
        'tax_value': 'float',
        'tax_value_after_discount': 'float',
        'options': 'list[OrderItemOption]',
        'variant_id': 'str',
        'weight_unit': 'str',
        'weight': 'float',
        'barcode': 'str',
        'parent_order_product_id': 'str',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'product_id': 'product_id',
        'order_product_id': 'order_product_id',
        'model': 'model',
        'name': 'name',
        'price': 'price',
        'price_inc_tax': 'price_inc_tax',
        'quantity': 'quantity',
        'discount_amount': 'discount_amount',
        'total_price': 'total_price',
        'tax_percent': 'tax_percent',
        'tax_value': 'tax_value',
        'tax_value_after_discount': 'tax_value_after_discount',
        'options': 'options',
        'variant_id': 'variant_id',
        'weight_unit': 'weight_unit',
        'weight': 'weight',
        'barcode': 'barcode',
        'parent_order_product_id': 'parent_order_product_id',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, product_id=None, order_product_id=None, model=None, name=None, price=None, price_inc_tax=None, quantity=None, discount_amount=None, total_price=None, tax_percent=None, tax_value=None, tax_value_after_discount=None, options=None, variant_id=None, weight_unit=None, weight=None, barcode=None, parent_order_product_id=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """OrderItem - a model defined in Swagger"""  # noqa: E501

        self._product_id = None
        self._order_product_id = None
        self._model = None
        self._name = None
        self._price = None
        self._price_inc_tax = None
        self._quantity = None
        self._discount_amount = None
        self._total_price = None
        self._tax_percent = None
        self._tax_value = None
        self._tax_value_after_discount = None
        self._options = None
        self._variant_id = None
        self._weight_unit = None
        self._weight = None
        self._barcode = None
        self._parent_order_product_id = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if product_id is not None:
            self.product_id = product_id
        if order_product_id is not None:
            self.order_product_id = order_product_id
        if model is not None:
            self.model = model
        if name is not None:
            self.name = name
        if price is not None:
            self.price = price
        if price_inc_tax is not None:
            self.price_inc_tax = price_inc_tax
        if quantity is not None:
            self.quantity = quantity
        if discount_amount is not None:
            self.discount_amount = discount_amount
        if total_price is not None:
            self.total_price = total_price
        if tax_percent is not None:
            self.tax_percent = tax_percent
        if tax_value is not None:
            self.tax_value = tax_value
        if tax_value_after_discount is not None:
            self.tax_value_after_discount = tax_value_after_discount
        if options is not None:
            self.options = options
        if variant_id is not None:
            self.variant_id = variant_id
        if weight_unit is not None:
            self.weight_unit = weight_unit
        if weight is not None:
            self.weight = weight
        if barcode is not None:
            self.barcode = barcode
        if parent_order_product_id is not None:
            self.parent_order_product_id = parent_order_product_id
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def product_id(self):
        """Gets the product_id of this OrderItem.  # noqa: E501


        :return: The product_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this OrderItem.


        :param product_id: The product_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._product_id = product_id

    @property
    def order_product_id(self):
        """Gets the order_product_id of this OrderItem.  # noqa: E501


        :return: The order_product_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._order_product_id

    @order_product_id.setter
    def order_product_id(self, order_product_id):
        """Sets the order_product_id of this OrderItem.


        :param order_product_id: The order_product_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._order_product_id = order_product_id

    @property
    def model(self):
        """Gets the model of this OrderItem.  # noqa: E501


        :return: The model of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this OrderItem.


        :param model: The model of this OrderItem.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def name(self):
        """Gets the name of this OrderItem.  # noqa: E501


        :return: The name of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrderItem.


        :param name: The name of this OrderItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def price(self):
        """Gets the price of this OrderItem.  # noqa: E501


        :return: The price of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderItem.


        :param price: The price of this OrderItem.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def price_inc_tax(self):
        """Gets the price_inc_tax of this OrderItem.  # noqa: E501


        :return: The price_inc_tax of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._price_inc_tax

    @price_inc_tax.setter
    def price_inc_tax(self, price_inc_tax):
        """Sets the price_inc_tax of this OrderItem.


        :param price_inc_tax: The price_inc_tax of this OrderItem.  # noqa: E501
        :type: float
        """

        self._price_inc_tax = price_inc_tax

    @property
    def quantity(self):
        """Gets the quantity of this OrderItem.  # noqa: E501


        :return: The quantity of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this OrderItem.


        :param quantity: The quantity of this OrderItem.  # noqa: E501
        :type: float
        """

        self._quantity = quantity

    @property
    def discount_amount(self):
        """Gets the discount_amount of this OrderItem.  # noqa: E501


        :return: The discount_amount of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._discount_amount

    @discount_amount.setter
    def discount_amount(self, discount_amount):
        """Sets the discount_amount of this OrderItem.


        :param discount_amount: The discount_amount of this OrderItem.  # noqa: E501
        :type: float
        """

        self._discount_amount = discount_amount

    @property
    def total_price(self):
        """Gets the total_price of this OrderItem.  # noqa: E501


        :return: The total_price of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this OrderItem.


        :param total_price: The total_price of this OrderItem.  # noqa: E501
        :type: float
        """

        self._total_price = total_price

    @property
    def tax_percent(self):
        """Gets the tax_percent of this OrderItem.  # noqa: E501


        :return: The tax_percent of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._tax_percent

    @tax_percent.setter
    def tax_percent(self, tax_percent):
        """Sets the tax_percent of this OrderItem.


        :param tax_percent: The tax_percent of this OrderItem.  # noqa: E501
        :type: float
        """

        self._tax_percent = tax_percent

    @property
    def tax_value(self):
        """Gets the tax_value of this OrderItem.  # noqa: E501


        :return: The tax_value of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._tax_value

    @tax_value.setter
    def tax_value(self, tax_value):
        """Sets the tax_value of this OrderItem.


        :param tax_value: The tax_value of this OrderItem.  # noqa: E501
        :type: float
        """

        self._tax_value = tax_value

    @property
    def tax_value_after_discount(self):
        """Gets the tax_value_after_discount of this OrderItem.  # noqa: E501


        :return: The tax_value_after_discount of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._tax_value_after_discount

    @tax_value_after_discount.setter
    def tax_value_after_discount(self, tax_value_after_discount):
        """Sets the tax_value_after_discount of this OrderItem.


        :param tax_value_after_discount: The tax_value_after_discount of this OrderItem.  # noqa: E501
        :type: float
        """

        self._tax_value_after_discount = tax_value_after_discount

    @property
    def options(self):
        """Gets the options of this OrderItem.  # noqa: E501


        :return: The options of this OrderItem.  # noqa: E501
        :rtype: list[OrderItemOption]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this OrderItem.


        :param options: The options of this OrderItem.  # noqa: E501
        :type: list[OrderItemOption]
        """

        self._options = options

    @property
    def variant_id(self):
        """Gets the variant_id of this OrderItem.  # noqa: E501


        :return: The variant_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._variant_id

    @variant_id.setter
    def variant_id(self, variant_id):
        """Sets the variant_id of this OrderItem.


        :param variant_id: The variant_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._variant_id = variant_id

    @property
    def weight_unit(self):
        """Gets the weight_unit of this OrderItem.  # noqa: E501


        :return: The weight_unit of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._weight_unit

    @weight_unit.setter
    def weight_unit(self, weight_unit):
        """Sets the weight_unit of this OrderItem.


        :param weight_unit: The weight_unit of this OrderItem.  # noqa: E501
        :type: str
        """

        self._weight_unit = weight_unit

    @property
    def weight(self):
        """Gets the weight of this OrderItem.  # noqa: E501


        :return: The weight of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this OrderItem.


        :param weight: The weight of this OrderItem.  # noqa: E501
        :type: float
        """

        self._weight = weight

    @property
    def barcode(self):
        """Gets the barcode of this OrderItem.  # noqa: E501


        :return: The barcode of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._barcode

    @barcode.setter
    def barcode(self, barcode):
        """Sets the barcode of this OrderItem.


        :param barcode: The barcode of this OrderItem.  # noqa: E501
        :type: str
        """

        self._barcode = barcode

    @property
    def parent_order_product_id(self):
        """Gets the parent_order_product_id of this OrderItem.  # noqa: E501


        :return: The parent_order_product_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._parent_order_product_id

    @parent_order_product_id.setter
    def parent_order_product_id(self, parent_order_product_id):
        """Sets the parent_order_product_id of this OrderItem.


        :param parent_order_product_id: The parent_order_product_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._parent_order_product_id = parent_order_product_id

    @property
    def additional_fields(self):
        """Gets the additional_fields of this OrderItem.  # noqa: E501


        :return: The additional_fields of this OrderItem.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this OrderItem.


        :param additional_fields: The additional_fields of this OrderItem.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this OrderItem.  # noqa: E501


        :return: The custom_fields of this OrderItem.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this OrderItem.


        :param custom_fields: The custom_fields of this OrderItem.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
