# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderRefund(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'shipping': 'float',
        'fee': 'float',
        'tax': 'float',
        'total': 'float',
        'modified_time': 'A2CDateTime',
        'comment': 'str',
        'items': 'list[OrderStatusRefundItem]',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'shipping': 'shipping',
        'fee': 'fee',
        'tax': 'tax',
        'total': 'total',
        'modified_time': 'modified_time',
        'comment': 'comment',
        'items': 'items',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, shipping=None, fee=None, tax=None, total=None, modified_time=None, comment=None, items=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """OrderRefund - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._shipping = None
        self._fee = None
        self._tax = None
        self._total = None
        self._modified_time = None
        self._comment = None
        self._items = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if shipping is not None:
            self.shipping = shipping
        if fee is not None:
            self.fee = fee
        if tax is not None:
            self.tax = tax
        if total is not None:
            self.total = total
        if modified_time is not None:
            self.modified_time = modified_time
        if comment is not None:
            self.comment = comment
        if items is not None:
            self.items = items
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this OrderRefund.  # noqa: E501


        :return: The id of this OrderRefund.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrderRefund.


        :param id: The id of this OrderRefund.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def shipping(self):
        """Gets the shipping of this OrderRefund.  # noqa: E501


        :return: The shipping of this OrderRefund.  # noqa: E501
        :rtype: float
        """
        return self._shipping

    @shipping.setter
    def shipping(self, shipping):
        """Sets the shipping of this OrderRefund.


        :param shipping: The shipping of this OrderRefund.  # noqa: E501
        :type: float
        """

        self._shipping = shipping

    @property
    def fee(self):
        """Gets the fee of this OrderRefund.  # noqa: E501


        :return: The fee of this OrderRefund.  # noqa: E501
        :rtype: float
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """Sets the fee of this OrderRefund.


        :param fee: The fee of this OrderRefund.  # noqa: E501
        :type: float
        """

        self._fee = fee

    @property
    def tax(self):
        """Gets the tax of this OrderRefund.  # noqa: E501


        :return: The tax of this OrderRefund.  # noqa: E501
        :rtype: float
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """Sets the tax of this OrderRefund.


        :param tax: The tax of this OrderRefund.  # noqa: E501
        :type: float
        """

        self._tax = tax

    @property
    def total(self):
        """Gets the total of this OrderRefund.  # noqa: E501


        :return: The total of this OrderRefund.  # noqa: E501
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this OrderRefund.


        :param total: The total of this OrderRefund.  # noqa: E501
        :type: float
        """

        self._total = total

    @property
    def modified_time(self):
        """Gets the modified_time of this OrderRefund.  # noqa: E501


        :return: The modified_time of this OrderRefund.  # noqa: E501
        :rtype: A2CDateTime
        """
        return self._modified_time

    @modified_time.setter
    def modified_time(self, modified_time):
        """Sets the modified_time of this OrderRefund.


        :param modified_time: The modified_time of this OrderRefund.  # noqa: E501
        :type: A2CDateTime
        """

        self._modified_time = modified_time

    @property
    def comment(self):
        """Gets the comment of this OrderRefund.  # noqa: E501


        :return: The comment of this OrderRefund.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this OrderRefund.


        :param comment: The comment of this OrderRefund.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def items(self):
        """Gets the items of this OrderRefund.  # noqa: E501


        :return: The items of this OrderRefund.  # noqa: E501
        :rtype: list[OrderStatusRefundItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this OrderRefund.


        :param items: The items of this OrderRefund.  # noqa: E501
        :type: list[OrderStatusRefundItem]
        """

        self._items = items

    @property
    def additional_fields(self):
        """Gets the additional_fields of this OrderRefund.  # noqa: E501


        :return: The additional_fields of this OrderRefund.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this OrderRefund.


        :param additional_fields: The additional_fields of this OrderRefund.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this OrderRefund.  # noqa: E501


        :return: The custom_fields of this OrderRefund.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this OrderRefund.


        :param custom_fields: The custom_fields of this OrderRefund.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderRefund, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderRefund):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
