# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderAdd(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'order_id': 'str',
        'store_id': 'str',
        'channel_id': 'str',
        'order_status': 'str',
        'send_notifications': 'bool',
        'send_admin_notifications': 'bool',
        'customer_email': 'str',
        'bill_first_name': 'str',
        'bill_last_name': 'str',
        'bill_address_1': 'str',
        'bill_city': 'str',
        'bill_postcode': 'str',
        'bill_state': 'str',
        'bill_country': 'str',
        'shipp_first_name': 'str',
        'shipp_last_name': 'str',
        'shipp_address_1': 'str',
        'shipp_city': 'str',
        'shipp_postcode': 'str',
        'shipp_state': 'str',
        'shipp_country': 'str',
        'total_price': 'float',
        '_date': 'str',
        'order_payment_method': 'str',
        'transaction_id': 'str',
        'order_shipping_method': 'str',
        'currency': 'str',
        'bill_address_2': 'str',
        'bill_company': 'str',
        'bill_phone': 'str',
        'bill_fax': 'str',
        'comment': 'str',
        'admin_comment': 'str',
        'admin_private_comment': 'str',
        'customer_first_name': 'str',
        'customer_last_name': 'str',
        'customer_birthday': 'str',
        'customer_fax': 'str',
        'customer_phone': 'str',
        'shipp_address_2': 'str',
        'shipp_company': 'str',
        'shipp_phone': 'str',
        'shipp_fax': 'str',
        'date_modified': 'str',
        'date_finished': 'str',
        'subtotal_price': 'float',
        'tax_price': 'float',
        'shipping_price': 'float',
        'shipping_tax': 'float',
        'discount': 'float',
        'coupon_discount': 'float',
        'gift_certificate_discount': 'float',
        'fulfillment_status': 'str',
        'financial_status': 'str',
        'total_paid': 'float',
        'external_source': 'str',
        'tags': 'str',
        'inventory_behaviour': 'str',
        'create_invoice': 'bool',
        'note_attributes': 'list[OrderAddNoteAttributes]',
        'total_weight': 'int',
        'clear_cache': 'bool',
        'order_item': 'list[OrderAddOrderItem]'
    }

    attribute_map = {
        'id': 'id',
        'order_id': 'order_id',
        'store_id': 'store_id',
        'channel_id': 'channel_id',
        'order_status': 'order_status',
        'send_notifications': 'send_notifications',
        'send_admin_notifications': 'send_admin_notifications',
        'customer_email': 'customer_email',
        'bill_first_name': 'bill_first_name',
        'bill_last_name': 'bill_last_name',
        'bill_address_1': 'bill_address_1',
        'bill_city': 'bill_city',
        'bill_postcode': 'bill_postcode',
        'bill_state': 'bill_state',
        'bill_country': 'bill_country',
        'shipp_first_name': 'shipp_first_name',
        'shipp_last_name': 'shipp_last_name',
        'shipp_address_1': 'shipp_address_1',
        'shipp_city': 'shipp_city',
        'shipp_postcode': 'shipp_postcode',
        'shipp_state': 'shipp_state',
        'shipp_country': 'shipp_country',
        'total_price': 'total_price',
        '_date': 'date',
        'order_payment_method': 'order_payment_method',
        'transaction_id': 'transaction_id',
        'order_shipping_method': 'order_shipping_method',
        'currency': 'currency',
        'bill_address_2': 'bill_address_2',
        'bill_company': 'bill_company',
        'bill_phone': 'bill_phone',
        'bill_fax': 'bill_fax',
        'comment': 'comment',
        'admin_comment': 'admin_comment',
        'admin_private_comment': 'admin_private_comment',
        'customer_first_name': 'customer_first_name',
        'customer_last_name': 'customer_last_name',
        'customer_birthday': 'customer_birthday',
        'customer_fax': 'customer_fax',
        'customer_phone': 'customer_phone',
        'shipp_address_2': 'shipp_address_2',
        'shipp_company': 'shipp_company',
        'shipp_phone': 'shipp_phone',
        'shipp_fax': 'shipp_fax',
        'date_modified': 'date_modified',
        'date_finished': 'date_finished',
        'subtotal_price': 'subtotal_price',
        'tax_price': 'tax_price',
        'shipping_price': 'shipping_price',
        'shipping_tax': 'shipping_tax',
        'discount': 'discount',
        'coupon_discount': 'coupon_discount',
        'gift_certificate_discount': 'gift_certificate_discount',
        'fulfillment_status': 'fulfillment_status',
        'financial_status': 'financial_status',
        'total_paid': 'total_paid',
        'external_source': 'external_source',
        'tags': 'tags',
        'inventory_behaviour': 'inventory_behaviour',
        'create_invoice': 'create_invoice',
        'note_attributes': 'note_attributes',
        'total_weight': 'total_weight',
        'clear_cache': 'clear_cache',
        'order_item': 'order_item'
    }

    def __init__(self, id=None, order_id=None, store_id=None, channel_id=None, order_status=None, send_notifications=False, send_admin_notifications=False, customer_email=None, bill_first_name=None, bill_last_name=None, bill_address_1=None, bill_city=None, bill_postcode=None, bill_state=None, bill_country=None, shipp_first_name=None, shipp_last_name=None, shipp_address_1=None, shipp_city=None, shipp_postcode=None, shipp_state=None, shipp_country=None, total_price=None, _date=None, order_payment_method=None, transaction_id=None, order_shipping_method=None, currency=None, bill_address_2=None, bill_company=None, bill_phone=None, bill_fax=None, comment=None, admin_comment=None, admin_private_comment=None, customer_first_name=None, customer_last_name=None, customer_birthday=None, customer_fax=None, customer_phone=None, shipp_address_2=None, shipp_company=None, shipp_phone=None, shipp_fax=None, date_modified=None, date_finished=None, subtotal_price=None, tax_price=None, shipping_price=None, shipping_tax=None, discount=None, coupon_discount=None, gift_certificate_discount=None, fulfillment_status=None, financial_status=None, total_paid=None, external_source=None, tags=None, inventory_behaviour='bypass', create_invoice=False, note_attributes=None, total_weight=None, clear_cache=True, order_item=None):  # noqa: E501
        """OrderAdd - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._order_id = None
        self._store_id = None
        self._channel_id = None
        self._order_status = None
        self._send_notifications = None
        self._send_admin_notifications = None
        self._customer_email = None
        self._bill_first_name = None
        self._bill_last_name = None
        self._bill_address_1 = None
        self._bill_city = None
        self._bill_postcode = None
        self._bill_state = None
        self._bill_country = None
        self._shipp_first_name = None
        self._shipp_last_name = None
        self._shipp_address_1 = None
        self._shipp_city = None
        self._shipp_postcode = None
        self._shipp_state = None
        self._shipp_country = None
        self._total_price = None
        self.__date = None
        self._order_payment_method = None
        self._transaction_id = None
        self._order_shipping_method = None
        self._currency = None
        self._bill_address_2 = None
        self._bill_company = None
        self._bill_phone = None
        self._bill_fax = None
        self._comment = None
        self._admin_comment = None
        self._admin_private_comment = None
        self._customer_first_name = None
        self._customer_last_name = None
        self._customer_birthday = None
        self._customer_fax = None
        self._customer_phone = None
        self._shipp_address_2 = None
        self._shipp_company = None
        self._shipp_phone = None
        self._shipp_fax = None
        self._date_modified = None
        self._date_finished = None
        self._subtotal_price = None
        self._tax_price = None
        self._shipping_price = None
        self._shipping_tax = None
        self._discount = None
        self._coupon_discount = None
        self._gift_certificate_discount = None
        self._fulfillment_status = None
        self._financial_status = None
        self._total_paid = None
        self._external_source = None
        self._tags = None
        self._inventory_behaviour = None
        self._create_invoice = None
        self._note_attributes = None
        self._total_weight = None
        self._clear_cache = None
        self._order_item = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if order_id is not None:
            self.order_id = order_id
        if store_id is not None:
            self.store_id = store_id
        if channel_id is not None:
            self.channel_id = channel_id
        self.order_status = order_status
        if send_notifications is not None:
            self.send_notifications = send_notifications
        if send_admin_notifications is not None:
            self.send_admin_notifications = send_admin_notifications
        self.customer_email = customer_email
        self.bill_first_name = bill_first_name
        self.bill_last_name = bill_last_name
        self.bill_address_1 = bill_address_1
        self.bill_city = bill_city
        self.bill_postcode = bill_postcode
        self.bill_state = bill_state
        self.bill_country = bill_country
        if shipp_first_name is not None:
            self.shipp_first_name = shipp_first_name
        if shipp_last_name is not None:
            self.shipp_last_name = shipp_last_name
        if shipp_address_1 is not None:
            self.shipp_address_1 = shipp_address_1
        if shipp_city is not None:
            self.shipp_city = shipp_city
        if shipp_postcode is not None:
            self.shipp_postcode = shipp_postcode
        if shipp_state is not None:
            self.shipp_state = shipp_state
        if shipp_country is not None:
            self.shipp_country = shipp_country
        if total_price is not None:
            self.total_price = total_price
        if _date is not None:
            self._date = _date
        if order_payment_method is not None:
            self.order_payment_method = order_payment_method
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if order_shipping_method is not None:
            self.order_shipping_method = order_shipping_method
        if currency is not None:
            self.currency = currency
        if bill_address_2 is not None:
            self.bill_address_2 = bill_address_2
        if bill_company is not None:
            self.bill_company = bill_company
        if bill_phone is not None:
            self.bill_phone = bill_phone
        if bill_fax is not None:
            self.bill_fax = bill_fax
        if comment is not None:
            self.comment = comment
        if admin_comment is not None:
            self.admin_comment = admin_comment
        if admin_private_comment is not None:
            self.admin_private_comment = admin_private_comment
        if customer_first_name is not None:
            self.customer_first_name = customer_first_name
        if customer_last_name is not None:
            self.customer_last_name = customer_last_name
        if customer_birthday is not None:
            self.customer_birthday = customer_birthday
        if customer_fax is not None:
            self.customer_fax = customer_fax
        if customer_phone is not None:
            self.customer_phone = customer_phone
        if shipp_address_2 is not None:
            self.shipp_address_2 = shipp_address_2
        if shipp_company is not None:
            self.shipp_company = shipp_company
        if shipp_phone is not None:
            self.shipp_phone = shipp_phone
        if shipp_fax is not None:
            self.shipp_fax = shipp_fax
        if date_modified is not None:
            self.date_modified = date_modified
        if date_finished is not None:
            self.date_finished = date_finished
        if subtotal_price is not None:
            self.subtotal_price = subtotal_price
        if tax_price is not None:
            self.tax_price = tax_price
        if shipping_price is not None:
            self.shipping_price = shipping_price
        if shipping_tax is not None:
            self.shipping_tax = shipping_tax
        if discount is not None:
            self.discount = discount
        if coupon_discount is not None:
            self.coupon_discount = coupon_discount
        if gift_certificate_discount is not None:
            self.gift_certificate_discount = gift_certificate_discount
        if fulfillment_status is not None:
            self.fulfillment_status = fulfillment_status
        if financial_status is not None:
            self.financial_status = financial_status
        if total_paid is not None:
            self.total_paid = total_paid
        if external_source is not None:
            self.external_source = external_source
        if tags is not None:
            self.tags = tags
        if inventory_behaviour is not None:
            self.inventory_behaviour = inventory_behaviour
        if create_invoice is not None:
            self.create_invoice = create_invoice
        if note_attributes is not None:
            self.note_attributes = note_attributes
        if total_weight is not None:
            self.total_weight = total_weight
        if clear_cache is not None:
            self.clear_cache = clear_cache
        self.order_item = order_item

    @property
    def id(self):
        """Gets the id of this OrderAdd.  # noqa: E501

        Defines order's id  # noqa: E501

        :return: The id of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrderAdd.

        Defines order's id  # noqa: E501

        :param id: The id of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def order_id(self):
        """Gets the order_id of this OrderAdd.  # noqa: E501

        Defines the order id if it is supported by the cart  # noqa: E501

        :return: The order_id of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this OrderAdd.

        Defines the order id if it is supported by the cart  # noqa: E501

        :param order_id: The order_id of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def store_id(self):
        """Gets the store_id of this OrderAdd.  # noqa: E501

        Defines store id where the order should be assigned  # noqa: E501

        :return: The store_id of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._store_id

    @store_id.setter
    def store_id(self, store_id):
        """Sets the store_id of this OrderAdd.

        Defines store id where the order should be assigned  # noqa: E501

        :param store_id: The store_id of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._store_id = store_id

    @property
    def channel_id(self):
        """Gets the channel_id of this OrderAdd.  # noqa: E501

        Channel ID  # noqa: E501

        :return: The channel_id of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this OrderAdd.

        Channel ID  # noqa: E501

        :param channel_id: The channel_id of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._channel_id = channel_id

    @property
    def order_status(self):
        """Gets the order_status of this OrderAdd.  # noqa: E501

        Defines order status.  # noqa: E501

        :return: The order_status of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._order_status

    @order_status.setter
    def order_status(self, order_status):
        """Sets the order_status of this OrderAdd.

        Defines order status.  # noqa: E501

        :param order_status: The order_status of this OrderAdd.  # noqa: E501
        :type: str
        """
        if order_status is None:
            raise ValueError("Invalid value for `order_status`, must not be `None`")  # noqa: E501

        self._order_status = order_status

    @property
    def send_notifications(self):
        """Gets the send_notifications of this OrderAdd.  # noqa: E501

        Send notifications to customer after order was created  # noqa: E501

        :return: The send_notifications of this OrderAdd.  # noqa: E501
        :rtype: bool
        """
        return self._send_notifications

    @send_notifications.setter
    def send_notifications(self, send_notifications):
        """Sets the send_notifications of this OrderAdd.

        Send notifications to customer after order was created  # noqa: E501

        :param send_notifications: The send_notifications of this OrderAdd.  # noqa: E501
        :type: bool
        """

        self._send_notifications = send_notifications

    @property
    def send_admin_notifications(self):
        """Gets the send_admin_notifications of this OrderAdd.  # noqa: E501

        Notify admin when new order was created.  # noqa: E501

        :return: The send_admin_notifications of this OrderAdd.  # noqa: E501
        :rtype: bool
        """
        return self._send_admin_notifications

    @send_admin_notifications.setter
    def send_admin_notifications(self, send_admin_notifications):
        """Sets the send_admin_notifications of this OrderAdd.

        Notify admin when new order was created.  # noqa: E501

        :param send_admin_notifications: The send_admin_notifications of this OrderAdd.  # noqa: E501
        :type: bool
        """

        self._send_admin_notifications = send_admin_notifications

    @property
    def customer_email(self):
        """Gets the customer_email of this OrderAdd.  # noqa: E501

        Defines the customer specified by email for whom order has to be created  # noqa: E501

        :return: The customer_email of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_email

    @customer_email.setter
    def customer_email(self, customer_email):
        """Sets the customer_email of this OrderAdd.

        Defines the customer specified by email for whom order has to be created  # noqa: E501

        :param customer_email: The customer_email of this OrderAdd.  # noqa: E501
        :type: str
        """
        if customer_email is None:
            raise ValueError("Invalid value for `customer_email`, must not be `None`")  # noqa: E501

        self._customer_email = customer_email

    @property
    def bill_first_name(self):
        """Gets the bill_first_name of this OrderAdd.  # noqa: E501

        Specifies billing first name  # noqa: E501

        :return: The bill_first_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_first_name

    @bill_first_name.setter
    def bill_first_name(self, bill_first_name):
        """Sets the bill_first_name of this OrderAdd.

        Specifies billing first name  # noqa: E501

        :param bill_first_name: The bill_first_name of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_first_name is None:
            raise ValueError("Invalid value for `bill_first_name`, must not be `None`")  # noqa: E501

        self._bill_first_name = bill_first_name

    @property
    def bill_last_name(self):
        """Gets the bill_last_name of this OrderAdd.  # noqa: E501

        Specifies billing last name  # noqa: E501

        :return: The bill_last_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_last_name

    @bill_last_name.setter
    def bill_last_name(self, bill_last_name):
        """Sets the bill_last_name of this OrderAdd.

        Specifies billing last name  # noqa: E501

        :param bill_last_name: The bill_last_name of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_last_name is None:
            raise ValueError("Invalid value for `bill_last_name`, must not be `None`")  # noqa: E501

        self._bill_last_name = bill_last_name

    @property
    def bill_address_1(self):
        """Gets the bill_address_1 of this OrderAdd.  # noqa: E501

        Specifies first billing address  # noqa: E501

        :return: The bill_address_1 of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_address_1

    @bill_address_1.setter
    def bill_address_1(self, bill_address_1):
        """Sets the bill_address_1 of this OrderAdd.

        Specifies first billing address  # noqa: E501

        :param bill_address_1: The bill_address_1 of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_address_1 is None:
            raise ValueError("Invalid value for `bill_address_1`, must not be `None`")  # noqa: E501

        self._bill_address_1 = bill_address_1

    @property
    def bill_city(self):
        """Gets the bill_city of this OrderAdd.  # noqa: E501

        Specifies billing city  # noqa: E501

        :return: The bill_city of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_city

    @bill_city.setter
    def bill_city(self, bill_city):
        """Sets the bill_city of this OrderAdd.

        Specifies billing city  # noqa: E501

        :param bill_city: The bill_city of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_city is None:
            raise ValueError("Invalid value for `bill_city`, must not be `None`")  # noqa: E501

        self._bill_city = bill_city

    @property
    def bill_postcode(self):
        """Gets the bill_postcode of this OrderAdd.  # noqa: E501

        Specifies billing postcode  # noqa: E501

        :return: The bill_postcode of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_postcode

    @bill_postcode.setter
    def bill_postcode(self, bill_postcode):
        """Sets the bill_postcode of this OrderAdd.

        Specifies billing postcode  # noqa: E501

        :param bill_postcode: The bill_postcode of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_postcode is None:
            raise ValueError("Invalid value for `bill_postcode`, must not be `None`")  # noqa: E501

        self._bill_postcode = bill_postcode

    @property
    def bill_state(self):
        """Gets the bill_state of this OrderAdd.  # noqa: E501

        Specifies billing state code  # noqa: E501

        :return: The bill_state of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_state

    @bill_state.setter
    def bill_state(self, bill_state):
        """Sets the bill_state of this OrderAdd.

        Specifies billing state code  # noqa: E501

        :param bill_state: The bill_state of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_state is None:
            raise ValueError("Invalid value for `bill_state`, must not be `None`")  # noqa: E501

        self._bill_state = bill_state

    @property
    def bill_country(self):
        """Gets the bill_country of this OrderAdd.  # noqa: E501

        Specifies billing country code  # noqa: E501

        :return: The bill_country of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_country

    @bill_country.setter
    def bill_country(self, bill_country):
        """Sets the bill_country of this OrderAdd.

        Specifies billing country code  # noqa: E501

        :param bill_country: The bill_country of this OrderAdd.  # noqa: E501
        :type: str
        """
        if bill_country is None:
            raise ValueError("Invalid value for `bill_country`, must not be `None`")  # noqa: E501

        self._bill_country = bill_country

    @property
    def shipp_first_name(self):
        """Gets the shipp_first_name of this OrderAdd.  # noqa: E501

        Specifies shipping first name  # noqa: E501

        :return: The shipp_first_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_first_name

    @shipp_first_name.setter
    def shipp_first_name(self, shipp_first_name):
        """Sets the shipp_first_name of this OrderAdd.

        Specifies shipping first name  # noqa: E501

        :param shipp_first_name: The shipp_first_name of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_first_name = shipp_first_name

    @property
    def shipp_last_name(self):
        """Gets the shipp_last_name of this OrderAdd.  # noqa: E501

        Specifies shipping last name  # noqa: E501

        :return: The shipp_last_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_last_name

    @shipp_last_name.setter
    def shipp_last_name(self, shipp_last_name):
        """Sets the shipp_last_name of this OrderAdd.

        Specifies shipping last name  # noqa: E501

        :param shipp_last_name: The shipp_last_name of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_last_name = shipp_last_name

    @property
    def shipp_address_1(self):
        """Gets the shipp_address_1 of this OrderAdd.  # noqa: E501

        Specifies first shipping address  # noqa: E501

        :return: The shipp_address_1 of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_address_1

    @shipp_address_1.setter
    def shipp_address_1(self, shipp_address_1):
        """Sets the shipp_address_1 of this OrderAdd.

        Specifies first shipping address  # noqa: E501

        :param shipp_address_1: The shipp_address_1 of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_address_1 = shipp_address_1

    @property
    def shipp_city(self):
        """Gets the shipp_city of this OrderAdd.  # noqa: E501

        Specifies shipping city  # noqa: E501

        :return: The shipp_city of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_city

    @shipp_city.setter
    def shipp_city(self, shipp_city):
        """Sets the shipp_city of this OrderAdd.

        Specifies shipping city  # noqa: E501

        :param shipp_city: The shipp_city of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_city = shipp_city

    @property
    def shipp_postcode(self):
        """Gets the shipp_postcode of this OrderAdd.  # noqa: E501

        Specifies shipping postcode  # noqa: E501

        :return: The shipp_postcode of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_postcode

    @shipp_postcode.setter
    def shipp_postcode(self, shipp_postcode):
        """Sets the shipp_postcode of this OrderAdd.

        Specifies shipping postcode  # noqa: E501

        :param shipp_postcode: The shipp_postcode of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_postcode = shipp_postcode

    @property
    def shipp_state(self):
        """Gets the shipp_state of this OrderAdd.  # noqa: E501

        Specifies shipping state code  # noqa: E501

        :return: The shipp_state of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_state

    @shipp_state.setter
    def shipp_state(self, shipp_state):
        """Sets the shipp_state of this OrderAdd.

        Specifies shipping state code  # noqa: E501

        :param shipp_state: The shipp_state of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_state = shipp_state

    @property
    def shipp_country(self):
        """Gets the shipp_country of this OrderAdd.  # noqa: E501

        Specifies shipping country code  # noqa: E501

        :return: The shipp_country of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_country

    @shipp_country.setter
    def shipp_country(self, shipp_country):
        """Sets the shipp_country of this OrderAdd.

        Specifies shipping country code  # noqa: E501

        :param shipp_country: The shipp_country of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_country = shipp_country

    @property
    def total_price(self):
        """Gets the total_price of this OrderAdd.  # noqa: E501

        Defines order's total price  # noqa: E501

        :return: The total_price of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this OrderAdd.

        Defines order's total price  # noqa: E501

        :param total_price: The total_price of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._total_price = total_price

    @property
    def _date(self):
        """Gets the _date of this OrderAdd.  # noqa: E501

        Specifies an order creation date in format Y-m-d H:i:s  # noqa: E501

        :return: The _date of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this OrderAdd.

        Specifies an order creation date in format Y-m-d H:i:s  # noqa: E501

        :param _date: The _date of this OrderAdd.  # noqa: E501
        :type: str
        """

        self.__date = _date

    @property
    def order_payment_method(self):
        """Gets the order_payment_method of this OrderAdd.  # noqa: E501

        Defines order payment method.<br/>Setting order_payment_method on Shopify will also change financial_status field value to 'paid'  # noqa: E501

        :return: The order_payment_method of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._order_payment_method

    @order_payment_method.setter
    def order_payment_method(self, order_payment_method):
        """Sets the order_payment_method of this OrderAdd.

        Defines order payment method.<br/>Setting order_payment_method on Shopify will also change financial_status field value to 'paid'  # noqa: E501

        :param order_payment_method: The order_payment_method of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._order_payment_method = order_payment_method

    @property
    def transaction_id(self):
        """Gets the transaction_id of this OrderAdd.  # noqa: E501

        Payment transaction id  # noqa: E501

        :return: The transaction_id of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this OrderAdd.

        Payment transaction id  # noqa: E501

        :param transaction_id: The transaction_id of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._transaction_id = transaction_id

    @property
    def order_shipping_method(self):
        """Gets the order_shipping_method of this OrderAdd.  # noqa: E501

        Defines order shipping method  # noqa: E501

        :return: The order_shipping_method of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._order_shipping_method

    @order_shipping_method.setter
    def order_shipping_method(self, order_shipping_method):
        """Sets the order_shipping_method of this OrderAdd.

        Defines order shipping method  # noqa: E501

        :param order_shipping_method: The order_shipping_method of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._order_shipping_method = order_shipping_method

    @property
    def currency(self):
        """Gets the currency of this OrderAdd.  # noqa: E501

        Currency code of order  # noqa: E501

        :return: The currency of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this OrderAdd.

        Currency code of order  # noqa: E501

        :param currency: The currency of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def bill_address_2(self):
        """Gets the bill_address_2 of this OrderAdd.  # noqa: E501

        Specifies second billing address  # noqa: E501

        :return: The bill_address_2 of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_address_2

    @bill_address_2.setter
    def bill_address_2(self, bill_address_2):
        """Sets the bill_address_2 of this OrderAdd.

        Specifies second billing address  # noqa: E501

        :param bill_address_2: The bill_address_2 of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._bill_address_2 = bill_address_2

    @property
    def bill_company(self):
        """Gets the bill_company of this OrderAdd.  # noqa: E501

        Specifies billing company  # noqa: E501

        :return: The bill_company of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_company

    @bill_company.setter
    def bill_company(self, bill_company):
        """Sets the bill_company of this OrderAdd.

        Specifies billing company  # noqa: E501

        :param bill_company: The bill_company of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._bill_company = bill_company

    @property
    def bill_phone(self):
        """Gets the bill_phone of this OrderAdd.  # noqa: E501

        Specifies billing phone  # noqa: E501

        :return: The bill_phone of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_phone

    @bill_phone.setter
    def bill_phone(self, bill_phone):
        """Sets the bill_phone of this OrderAdd.

        Specifies billing phone  # noqa: E501

        :param bill_phone: The bill_phone of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._bill_phone = bill_phone

    @property
    def bill_fax(self):
        """Gets the bill_fax of this OrderAdd.  # noqa: E501

        Specifies billing fax  # noqa: E501

        :return: The bill_fax of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._bill_fax

    @bill_fax.setter
    def bill_fax(self, bill_fax):
        """Sets the bill_fax of this OrderAdd.

        Specifies billing fax  # noqa: E501

        :param bill_fax: The bill_fax of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._bill_fax = bill_fax

    @property
    def comment(self):
        """Gets the comment of this OrderAdd.  # noqa: E501

        Specifies order comment  # noqa: E501

        :return: The comment of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this OrderAdd.

        Specifies order comment  # noqa: E501

        :param comment: The comment of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def admin_comment(self):
        """Gets the admin_comment of this OrderAdd.  # noqa: E501

        Specifies admin's order comment  # noqa: E501

        :return: The admin_comment of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._admin_comment

    @admin_comment.setter
    def admin_comment(self, admin_comment):
        """Sets the admin_comment of this OrderAdd.

        Specifies admin's order comment  # noqa: E501

        :param admin_comment: The admin_comment of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._admin_comment = admin_comment

    @property
    def admin_private_comment(self):
        """Gets the admin_private_comment of this OrderAdd.  # noqa: E501

        Specifies private admin's order comment  # noqa: E501

        :return: The admin_private_comment of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._admin_private_comment

    @admin_private_comment.setter
    def admin_private_comment(self, admin_private_comment):
        """Sets the admin_private_comment of this OrderAdd.

        Specifies private admin's order comment  # noqa: E501

        :param admin_private_comment: The admin_private_comment of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._admin_private_comment = admin_private_comment

    @property
    def customer_first_name(self):
        """Gets the customer_first_name of this OrderAdd.  # noqa: E501

        Specifies customer's first name  # noqa: E501

        :return: The customer_first_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_first_name

    @customer_first_name.setter
    def customer_first_name(self, customer_first_name):
        """Sets the customer_first_name of this OrderAdd.

        Specifies customer's first name  # noqa: E501

        :param customer_first_name: The customer_first_name of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._customer_first_name = customer_first_name

    @property
    def customer_last_name(self):
        """Gets the customer_last_name of this OrderAdd.  # noqa: E501

        Specifies customer’s last name  # noqa: E501

        :return: The customer_last_name of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_last_name

    @customer_last_name.setter
    def customer_last_name(self, customer_last_name):
        """Sets the customer_last_name of this OrderAdd.

        Specifies customer’s last name  # noqa: E501

        :param customer_last_name: The customer_last_name of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._customer_last_name = customer_last_name

    @property
    def customer_birthday(self):
        """Gets the customer_birthday of this OrderAdd.  # noqa: E501

        Specifies customer’s birthday  # noqa: E501

        :return: The customer_birthday of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_birthday

    @customer_birthday.setter
    def customer_birthday(self, customer_birthday):
        """Sets the customer_birthday of this OrderAdd.

        Specifies customer’s birthday  # noqa: E501

        :param customer_birthday: The customer_birthday of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._customer_birthday = customer_birthday

    @property
    def customer_fax(self):
        """Gets the customer_fax of this OrderAdd.  # noqa: E501

        Specifies customer’s fax  # noqa: E501

        :return: The customer_fax of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_fax

    @customer_fax.setter
    def customer_fax(self, customer_fax):
        """Sets the customer_fax of this OrderAdd.

        Specifies customer’s fax  # noqa: E501

        :param customer_fax: The customer_fax of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._customer_fax = customer_fax

    @property
    def customer_phone(self):
        """Gets the customer_phone of this OrderAdd.  # noqa: E501

        Specifies customer’s phone  # noqa: E501

        :return: The customer_phone of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._customer_phone

    @customer_phone.setter
    def customer_phone(self, customer_phone):
        """Sets the customer_phone of this OrderAdd.

        Specifies customer’s phone  # noqa: E501

        :param customer_phone: The customer_phone of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._customer_phone = customer_phone

    @property
    def shipp_address_2(self):
        """Gets the shipp_address_2 of this OrderAdd.  # noqa: E501

        Specifies second address line of a shipping street address  # noqa: E501

        :return: The shipp_address_2 of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_address_2

    @shipp_address_2.setter
    def shipp_address_2(self, shipp_address_2):
        """Sets the shipp_address_2 of this OrderAdd.

        Specifies second address line of a shipping street address  # noqa: E501

        :param shipp_address_2: The shipp_address_2 of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_address_2 = shipp_address_2

    @property
    def shipp_company(self):
        """Gets the shipp_company of this OrderAdd.  # noqa: E501

        Specifies shipping company  # noqa: E501

        :return: The shipp_company of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_company

    @shipp_company.setter
    def shipp_company(self, shipp_company):
        """Sets the shipp_company of this OrderAdd.

        Specifies shipping company  # noqa: E501

        :param shipp_company: The shipp_company of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_company = shipp_company

    @property
    def shipp_phone(self):
        """Gets the shipp_phone of this OrderAdd.  # noqa: E501

        Specifies shipping phone  # noqa: E501

        :return: The shipp_phone of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_phone

    @shipp_phone.setter
    def shipp_phone(self, shipp_phone):
        """Sets the shipp_phone of this OrderAdd.

        Specifies shipping phone  # noqa: E501

        :param shipp_phone: The shipp_phone of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_phone = shipp_phone

    @property
    def shipp_fax(self):
        """Gets the shipp_fax of this OrderAdd.  # noqa: E501

        Specifies shipping fax  # noqa: E501

        :return: The shipp_fax of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._shipp_fax

    @shipp_fax.setter
    def shipp_fax(self, shipp_fax):
        """Sets the shipp_fax of this OrderAdd.

        Specifies shipping fax  # noqa: E501

        :param shipp_fax: The shipp_fax of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._shipp_fax = shipp_fax

    @property
    def date_modified(self):
        """Gets the date_modified of this OrderAdd.  # noqa: E501

        Specifies order's  modification date  # noqa: E501

        :return: The date_modified of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this OrderAdd.

        Specifies order's  modification date  # noqa: E501

        :param date_modified: The date_modified of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    @property
    def date_finished(self):
        """Gets the date_finished of this OrderAdd.  # noqa: E501

        Specifies order's  finished date  # noqa: E501

        :return: The date_finished of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._date_finished

    @date_finished.setter
    def date_finished(self, date_finished):
        """Sets the date_finished of this OrderAdd.

        Specifies order's  finished date  # noqa: E501

        :param date_finished: The date_finished of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._date_finished = date_finished

    @property
    def subtotal_price(self):
        """Gets the subtotal_price of this OrderAdd.  # noqa: E501

        Total price of all ordered products multiplied by their number, excluding tax, shipping price and discounts  # noqa: E501

        :return: The subtotal_price of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._subtotal_price

    @subtotal_price.setter
    def subtotal_price(self, subtotal_price):
        """Sets the subtotal_price of this OrderAdd.

        Total price of all ordered products multiplied by their number, excluding tax, shipping price and discounts  # noqa: E501

        :param subtotal_price: The subtotal_price of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._subtotal_price = subtotal_price

    @property
    def tax_price(self):
        """Gets the tax_price of this OrderAdd.  # noqa: E501

        The value of tax cost for order  # noqa: E501

        :return: The tax_price of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._tax_price

    @tax_price.setter
    def tax_price(self, tax_price):
        """Sets the tax_price of this OrderAdd.

        The value of tax cost for order  # noqa: E501

        :param tax_price: The tax_price of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._tax_price = tax_price

    @property
    def shipping_price(self):
        """Gets the shipping_price of this OrderAdd.  # noqa: E501

        Specifies order's shipping price  # noqa: E501

        :return: The shipping_price of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._shipping_price

    @shipping_price.setter
    def shipping_price(self, shipping_price):
        """Sets the shipping_price of this OrderAdd.

        Specifies order's shipping price  # noqa: E501

        :param shipping_price: The shipping_price of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._shipping_price = shipping_price

    @property
    def shipping_tax(self):
        """Gets the shipping_tax of this OrderAdd.  # noqa: E501

        Specifies order's shipping price tax  # noqa: E501

        :return: The shipping_tax of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._shipping_tax

    @shipping_tax.setter
    def shipping_tax(self, shipping_tax):
        """Sets the shipping_tax of this OrderAdd.

        Specifies order's shipping price tax  # noqa: E501

        :param shipping_tax: The shipping_tax of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._shipping_tax = shipping_tax

    @property
    def discount(self):
        """Gets the discount of this OrderAdd.  # noqa: E501

        Specifies order's discount  # noqa: E501

        :return: The discount of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._discount

    @discount.setter
    def discount(self, discount):
        """Sets the discount of this OrderAdd.

        Specifies order's discount  # noqa: E501

        :param discount: The discount of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._discount = discount

    @property
    def coupon_discount(self):
        """Gets the coupon_discount of this OrderAdd.  # noqa: E501

        Specifies order's coupon discount  # noqa: E501

        :return: The coupon_discount of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._coupon_discount

    @coupon_discount.setter
    def coupon_discount(self, coupon_discount):
        """Sets the coupon_discount of this OrderAdd.

        Specifies order's coupon discount  # noqa: E501

        :param coupon_discount: The coupon_discount of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._coupon_discount = coupon_discount

    @property
    def gift_certificate_discount(self):
        """Gets the gift_certificate_discount of this OrderAdd.  # noqa: E501

        Discounts for order with gift certificates  # noqa: E501

        :return: The gift_certificate_discount of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._gift_certificate_discount

    @gift_certificate_discount.setter
    def gift_certificate_discount(self, gift_certificate_discount):
        """Sets the gift_certificate_discount of this OrderAdd.

        Discounts for order with gift certificates  # noqa: E501

        :param gift_certificate_discount: The gift_certificate_discount of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._gift_certificate_discount = gift_certificate_discount

    @property
    def fulfillment_status(self):
        """Gets the fulfillment_status of this OrderAdd.  # noqa: E501

        Create order with fulfillment status  # noqa: E501

        :return: The fulfillment_status of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._fulfillment_status

    @fulfillment_status.setter
    def fulfillment_status(self, fulfillment_status):
        """Sets the fulfillment_status of this OrderAdd.

        Create order with fulfillment status  # noqa: E501

        :param fulfillment_status: The fulfillment_status of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._fulfillment_status = fulfillment_status

    @property
    def financial_status(self):
        """Gets the financial_status of this OrderAdd.  # noqa: E501

        Create order with financial status  # noqa: E501

        :return: The financial_status of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._financial_status

    @financial_status.setter
    def financial_status(self, financial_status):
        """Sets the financial_status of this OrderAdd.

        Create order with financial status  # noqa: E501

        :param financial_status: The financial_status of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._financial_status = financial_status

    @property
    def total_paid(self):
        """Gets the total_paid of this OrderAdd.  # noqa: E501

        Defines total paid amount for the order  # noqa: E501

        :return: The total_paid of this OrderAdd.  # noqa: E501
        :rtype: float
        """
        return self._total_paid

    @total_paid.setter
    def total_paid(self, total_paid):
        """Sets the total_paid of this OrderAdd.

        Defines total paid amount for the order  # noqa: E501

        :param total_paid: The total_paid of this OrderAdd.  # noqa: E501
        :type: float
        """

        self._total_paid = total_paid

    @property
    def external_source(self):
        """Gets the external_source of this OrderAdd.  # noqa: E501

        Identifying the system used to generate the order  # noqa: E501

        :return: The external_source of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._external_source

    @external_source.setter
    def external_source(self, external_source):
        """Sets the external_source of this OrderAdd.

        Identifying the system used to generate the order  # noqa: E501

        :param external_source: The external_source of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._external_source = external_source

    @property
    def tags(self):
        """Gets the tags of this OrderAdd.  # noqa: E501

        Order tags  # noqa: E501

        :return: The tags of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this OrderAdd.

        Order tags  # noqa: E501

        :param tags: The tags of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._tags = tags

    @property
    def inventory_behaviour(self):
        """Gets the inventory_behaviour of this OrderAdd.  # noqa: E501

        The behaviour to use when updating inventory.<hr><div style=\"font-style:normal\">Values description:<div style=\"margin-left: 2%; padding-top: 2%\"><div style=\"font-size:85%\"><b>bypass</b> = Do not claim inventory </br></br><b>decrement_ignoring_policy</b> = Ignore the product's </br> inventory policy and claim amounts</br></br><b>decrement_obeying_policy</b> =  Obey the product's </br> inventory policy.</br></br></div></div></div>  # noqa: E501

        :return: The inventory_behaviour of this OrderAdd.  # noqa: E501
        :rtype: str
        """
        return self._inventory_behaviour

    @inventory_behaviour.setter
    def inventory_behaviour(self, inventory_behaviour):
        """Sets the inventory_behaviour of this OrderAdd.

        The behaviour to use when updating inventory.<hr><div style=\"font-style:normal\">Values description:<div style=\"margin-left: 2%; padding-top: 2%\"><div style=\"font-size:85%\"><b>bypass</b> = Do not claim inventory </br></br><b>decrement_ignoring_policy</b> = Ignore the product's </br> inventory policy and claim amounts</br></br><b>decrement_obeying_policy</b> =  Obey the product's </br> inventory policy.</br></br></div></div></div>  # noqa: E501

        :param inventory_behaviour: The inventory_behaviour of this OrderAdd.  # noqa: E501
        :type: str
        """

        self._inventory_behaviour = inventory_behaviour

    @property
    def create_invoice(self):
        """Gets the create_invoice of this OrderAdd.  # noqa: E501

        Defines whether the invoice is created automatically along with the order  # noqa: E501

        :return: The create_invoice of this OrderAdd.  # noqa: E501
        :rtype: bool
        """
        return self._create_invoice

    @create_invoice.setter
    def create_invoice(self, create_invoice):
        """Sets the create_invoice of this OrderAdd.

        Defines whether the invoice is created automatically along with the order  # noqa: E501

        :param create_invoice: The create_invoice of this OrderAdd.  # noqa: E501
        :type: bool
        """

        self._create_invoice = create_invoice

    @property
    def note_attributes(self):
        """Gets the note_attributes of this OrderAdd.  # noqa: E501

        Defines note attributes  # noqa: E501

        :return: The note_attributes of this OrderAdd.  # noqa: E501
        :rtype: list[OrderAddNoteAttributes]
        """
        return self._note_attributes

    @note_attributes.setter
    def note_attributes(self, note_attributes):
        """Sets the note_attributes of this OrderAdd.

        Defines note attributes  # noqa: E501

        :param note_attributes: The note_attributes of this OrderAdd.  # noqa: E501
        :type: list[OrderAddNoteAttributes]
        """

        self._note_attributes = note_attributes

    @property
    def total_weight(self):
        """Gets the total_weight of this OrderAdd.  # noqa: E501

        Defines the sum of all line item weights in grams for the order  # noqa: E501

        :return: The total_weight of this OrderAdd.  # noqa: E501
        :rtype: int
        """
        return self._total_weight

    @total_weight.setter
    def total_weight(self, total_weight):
        """Sets the total_weight of this OrderAdd.

        Defines the sum of all line item weights in grams for the order  # noqa: E501

        :param total_weight: The total_weight of this OrderAdd.  # noqa: E501
        :type: int
        """

        self._total_weight = total_weight

    @property
    def clear_cache(self):
        """Gets the clear_cache of this OrderAdd.  # noqa: E501

        Is cache clear required  # noqa: E501

        :return: The clear_cache of this OrderAdd.  # noqa: E501
        :rtype: bool
        """
        return self._clear_cache

    @clear_cache.setter
    def clear_cache(self, clear_cache):
        """Sets the clear_cache of this OrderAdd.

        Is cache clear required  # noqa: E501

        :param clear_cache: The clear_cache of this OrderAdd.  # noqa: E501
        :type: bool
        """

        self._clear_cache = clear_cache

    @property
    def order_item(self):
        """Gets the order_item of this OrderAdd.  # noqa: E501


        :return: The order_item of this OrderAdd.  # noqa: E501
        :rtype: list[OrderAddOrderItem]
        """
        return self._order_item

    @order_item.setter
    def order_item(self, order_item):
        """Sets the order_item of this OrderAdd.


        :param order_item: The order_item of this OrderAdd.  # noqa: E501
        :type: list[OrderAddOrderItem]
        """
        if order_item is None:
            raise ValueError("Invalid value for `order_item`, must not be `None`")  # noqa: E501

        self._order_item = order_item

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderAdd, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderAdd):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
