# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderAddOrderItemOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_item_option_name': 'str',
        'order_item_option_value': 'str',
        'order_item_option_price': 'float'
    }

    attribute_map = {
        'order_item_option_name': 'order_item_option_name',
        'order_item_option_value': 'order_item_option_value',
        'order_item_option_price': 'order_item_option_price'
    }

    def __init__(self, order_item_option_name=None, order_item_option_value=None, order_item_option_price=None):  # noqa: E501
        """OrderAddOrderItemOption - a model defined in Swagger"""  # noqa: E501

        self._order_item_option_name = None
        self._order_item_option_value = None
        self._order_item_option_price = None
        self.discriminator = None

        if order_item_option_name is not None:
            self.order_item_option_name = order_item_option_name
        if order_item_option_value is not None:
            self.order_item_option_value = order_item_option_value
        if order_item_option_price is not None:
            self.order_item_option_price = order_item_option_price

    @property
    def order_item_option_name(self):
        """Gets the order_item_option_name of this OrderAddOrderItemOption.  # noqa: E501

        Ordered Product Option Name. Where x is order item ID, y is order item option ID  # noqa: E501

        :return: The order_item_option_name of this OrderAddOrderItemOption.  # noqa: E501
        :rtype: str
        """
        return self._order_item_option_name

    @order_item_option_name.setter
    def order_item_option_name(self, order_item_option_name):
        """Sets the order_item_option_name of this OrderAddOrderItemOption.

        Ordered Product Option Name. Where x is order item ID, y is order item option ID  # noqa: E501

        :param order_item_option_name: The order_item_option_name of this OrderAddOrderItemOption.  # noqa: E501
        :type: str
        """

        self._order_item_option_name = order_item_option_name

    @property
    def order_item_option_value(self):
        """Gets the order_item_option_value of this OrderAddOrderItemOption.  # noqa: E501

        Ordered product option value Where x is order item ID, y - order item option ID  # noqa: E501

        :return: The order_item_option_value of this OrderAddOrderItemOption.  # noqa: E501
        :rtype: str
        """
        return self._order_item_option_value

    @order_item_option_value.setter
    def order_item_option_value(self, order_item_option_value):
        """Sets the order_item_option_value of this OrderAddOrderItemOption.

        Ordered product option value Where x is order item ID, y - order item option ID  # noqa: E501

        :param order_item_option_value: The order_item_option_value of this OrderAddOrderItemOption.  # noqa: E501
        :type: str
        """

        self._order_item_option_value = order_item_option_value

    @property
    def order_item_option_price(self):
        """Gets the order_item_option_price of this OrderAddOrderItemOption.  # noqa: E501

        Ordered product option price Where x is order item ID, y - order item option ID  # noqa: E501

        :return: The order_item_option_price of this OrderAddOrderItemOption.  # noqa: E501
        :rtype: float
        """
        return self._order_item_option_price

    @order_item_option_price.setter
    def order_item_option_price(self, order_item_option_price):
        """Sets the order_item_option_price of this OrderAddOrderItemOption.

        Ordered product option price Where x is order item ID, y - order item option ID  # noqa: E501

        :param order_item_option_price: The order_item_option_price of this OrderAddOrderItemOption.  # noqa: E501
        :type: float
        """

        self._order_item_option_price = order_item_option_price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderAddOrderItemOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderAddOrderItemOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
