# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderStatusHistoryItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'modified_time': 'A2CDateTime',
        'notify': 'bool',
        'comment': 'str',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'modified_time': 'modified_time',
        'notify': 'notify',
        'comment': 'comment',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, name=None, modified_time=None, notify=None, comment=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """OrderStatusHistoryItem - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._modified_time = None
        self._notify = None
        self._comment = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if modified_time is not None:
            self.modified_time = modified_time
        if notify is not None:
            self.notify = notify
        if comment is not None:
            self.comment = comment
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this OrderStatusHistoryItem.  # noqa: E501


        :return: The id of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrderStatusHistoryItem.


        :param id: The id of this OrderStatusHistoryItem.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OrderStatusHistoryItem.  # noqa: E501


        :return: The name of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrderStatusHistoryItem.


        :param name: The name of this OrderStatusHistoryItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def modified_time(self):
        """Gets the modified_time of this OrderStatusHistoryItem.  # noqa: E501


        :return: The modified_time of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: A2CDateTime
        """
        return self._modified_time

    @modified_time.setter
    def modified_time(self, modified_time):
        """Sets the modified_time of this OrderStatusHistoryItem.


        :param modified_time: The modified_time of this OrderStatusHistoryItem.  # noqa: E501
        :type: A2CDateTime
        """

        self._modified_time = modified_time

    @property
    def notify(self):
        """Gets the notify of this OrderStatusHistoryItem.  # noqa: E501


        :return: The notify of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: bool
        """
        return self._notify

    @notify.setter
    def notify(self, notify):
        """Sets the notify of this OrderStatusHistoryItem.


        :param notify: The notify of this OrderStatusHistoryItem.  # noqa: E501
        :type: bool
        """

        self._notify = notify

    @property
    def comment(self):
        """Gets the comment of this OrderStatusHistoryItem.  # noqa: E501


        :return: The comment of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this OrderStatusHistoryItem.


        :param comment: The comment of this OrderStatusHistoryItem.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def additional_fields(self):
        """Gets the additional_fields of this OrderStatusHistoryItem.  # noqa: E501


        :return: The additional_fields of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this OrderStatusHistoryItem.


        :param additional_fields: The additional_fields of this OrderStatusHistoryItem.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this OrderStatusHistoryItem.  # noqa: E501


        :return: The custom_fields of this OrderStatusHistoryItem.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this OrderStatusHistoryItem.


        :param custom_fields: The custom_fields of this OrderStatusHistoryItem.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderStatusHistoryItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderStatusHistoryItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
