# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductAdvancedPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'value': 'float',
        'avail': 'bool',
        'group_id': 'str',
        'quantity_from': 'float',
        'start_time': 'A2CDateTime',
        'expire_time': 'A2CDateTime',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'value': 'value',
        'avail': 'avail',
        'group_id': 'group_id',
        'quantity_from': 'quantity_from',
        'start_time': 'start_time',
        'expire_time': 'expire_time',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, value=None, avail=None, group_id=None, quantity_from=None, start_time=None, expire_time=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """ProductAdvancedPrice - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._value = None
        self._avail = None
        self._group_id = None
        self._quantity_from = None
        self._start_time = None
        self._expire_time = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if value is not None:
            self.value = value
        if avail is not None:
            self.avail = avail
        if group_id is not None:
            self.group_id = group_id
        if quantity_from is not None:
            self.quantity_from = quantity_from
        if start_time is not None:
            self.start_time = start_time
        if expire_time is not None:
            self.expire_time = expire_time
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this ProductAdvancedPrice.  # noqa: E501


        :return: The id of this ProductAdvancedPrice.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductAdvancedPrice.


        :param id: The id of this ProductAdvancedPrice.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def value(self):
        """Gets the value of this ProductAdvancedPrice.  # noqa: E501


        :return: The value of this ProductAdvancedPrice.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ProductAdvancedPrice.


        :param value: The value of this ProductAdvancedPrice.  # noqa: E501
        :type: float
        """

        self._value = value

    @property
    def avail(self):
        """Gets the avail of this ProductAdvancedPrice.  # noqa: E501


        :return: The avail of this ProductAdvancedPrice.  # noqa: E501
        :rtype: bool
        """
        return self._avail

    @avail.setter
    def avail(self, avail):
        """Sets the avail of this ProductAdvancedPrice.


        :param avail: The avail of this ProductAdvancedPrice.  # noqa: E501
        :type: bool
        """

        self._avail = avail

    @property
    def group_id(self):
        """Gets the group_id of this ProductAdvancedPrice.  # noqa: E501


        :return: The group_id of this ProductAdvancedPrice.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ProductAdvancedPrice.


        :param group_id: The group_id of this ProductAdvancedPrice.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def quantity_from(self):
        """Gets the quantity_from of this ProductAdvancedPrice.  # noqa: E501


        :return: The quantity_from of this ProductAdvancedPrice.  # noqa: E501
        :rtype: float
        """
        return self._quantity_from

    @quantity_from.setter
    def quantity_from(self, quantity_from):
        """Sets the quantity_from of this ProductAdvancedPrice.


        :param quantity_from: The quantity_from of this ProductAdvancedPrice.  # noqa: E501
        :type: float
        """

        self._quantity_from = quantity_from

    @property
    def start_time(self):
        """Gets the start_time of this ProductAdvancedPrice.  # noqa: E501


        :return: The start_time of this ProductAdvancedPrice.  # noqa: E501
        :rtype: A2CDateTime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ProductAdvancedPrice.


        :param start_time: The start_time of this ProductAdvancedPrice.  # noqa: E501
        :type: A2CDateTime
        """

        self._start_time = start_time

    @property
    def expire_time(self):
        """Gets the expire_time of this ProductAdvancedPrice.  # noqa: E501


        :return: The expire_time of this ProductAdvancedPrice.  # noqa: E501
        :rtype: A2CDateTime
        """
        return self._expire_time

    @expire_time.setter
    def expire_time(self, expire_time):
        """Sets the expire_time of this ProductAdvancedPrice.


        :param expire_time: The expire_time of this ProductAdvancedPrice.  # noqa: E501
        :type: A2CDateTime
        """

        self._expire_time = expire_time

    @property
    def additional_fields(self):
        """Gets the additional_fields of this ProductAdvancedPrice.  # noqa: E501


        :return: The additional_fields of this ProductAdvancedPrice.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this ProductAdvancedPrice.


        :param additional_fields: The additional_fields of this ProductAdvancedPrice.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this ProductAdvancedPrice.  # noqa: E501


        :return: The custom_fields of this ProductAdvancedPrice.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this ProductAdvancedPrice.


        :param custom_fields: The custom_fields of this ProductAdvancedPrice.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductAdvancedPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductAdvancedPrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
