# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductVariantPriceUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'group_prices': 'list[ProductPriceUpdateGroupPrices]'
    }

    attribute_map = {
        'id': 'id',
        'group_prices': 'group_prices'
    }

    def __init__(self, id=None, group_prices=None):  # noqa: E501
        """ProductVariantPriceUpdate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._group_prices = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if group_prices is not None:
            self.group_prices = group_prices

    @property
    def id(self):
        """Gets the id of this ProductVariantPriceUpdate.  # noqa: E501

        Defines the variant where the price has to be updated  # noqa: E501

        :return: The id of this ProductVariantPriceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductVariantPriceUpdate.

        Defines the variant where the price has to be updated  # noqa: E501

        :param id: The id of this ProductVariantPriceUpdate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def group_prices(self):
        """Gets the group_prices of this ProductVariantPriceUpdate.  # noqa: E501

        Defines variants's group prices  # noqa: E501

        :return: The group_prices of this ProductVariantPriceUpdate.  # noqa: E501
        :rtype: list[ProductPriceUpdateGroupPrices]
        """
        return self._group_prices

    @group_prices.setter
    def group_prices(self, group_prices):
        """Sets the group_prices of this ProductVariantPriceUpdate.

        Defines variants's group prices  # noqa: E501

        :param group_prices: The group_prices of this ProductVariantPriceUpdate.  # noqa: E501
        :type: list[ProductPriceUpdateGroupPrices]
        """

        self._group_prices = group_prices

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductVariantPriceUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductVariantPriceUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
