# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductOptionItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'product_option_item_id': 'str',
        'name': 'str',
        'sort_order': 'int',
        'price': 'str',
        'weight': 'str',
        'quantity': 'int',
        'type_price': 'str',
        'sku': 'str',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'product_option_item_id': 'product_option_item_id',
        'name': 'name',
        'sort_order': 'sort_order',
        'price': 'price',
        'weight': 'weight',
        'quantity': 'quantity',
        'type_price': 'type_price',
        'sku': 'sku',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, product_option_item_id=None, name=None, sort_order=None, price=None, weight=None, quantity=None, type_price=None, sku=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """ProductOptionItem - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._product_option_item_id = None
        self._name = None
        self._sort_order = None
        self._price = None
        self._weight = None
        self._quantity = None
        self._type_price = None
        self._sku = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if product_option_item_id is not None:
            self.product_option_item_id = product_option_item_id
        if name is not None:
            self.name = name
        if sort_order is not None:
            self.sort_order = sort_order
        if price is not None:
            self.price = price
        if weight is not None:
            self.weight = weight
        if quantity is not None:
            self.quantity = quantity
        if type_price is not None:
            self.type_price = type_price
        if sku is not None:
            self.sku = sku
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this ProductOptionItem.  # noqa: E501


        :return: The id of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductOptionItem.


        :param id: The id of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def product_option_item_id(self):
        """Gets the product_option_item_id of this ProductOptionItem.  # noqa: E501


        :return: The product_option_item_id of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._product_option_item_id

    @product_option_item_id.setter
    def product_option_item_id(self, product_option_item_id):
        """Sets the product_option_item_id of this ProductOptionItem.


        :param product_option_item_id: The product_option_item_id of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._product_option_item_id = product_option_item_id

    @property
    def name(self):
        """Gets the name of this ProductOptionItem.  # noqa: E501


        :return: The name of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductOptionItem.


        :param name: The name of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def sort_order(self):
        """Gets the sort_order of this ProductOptionItem.  # noqa: E501


        :return: The sort_order of this ProductOptionItem.  # noqa: E501
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this ProductOptionItem.


        :param sort_order: The sort_order of this ProductOptionItem.  # noqa: E501
        :type: int
        """

        self._sort_order = sort_order

    @property
    def price(self):
        """Gets the price of this ProductOptionItem.  # noqa: E501


        :return: The price of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ProductOptionItem.


        :param price: The price of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def weight(self):
        """Gets the weight of this ProductOptionItem.  # noqa: E501


        :return: The weight of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this ProductOptionItem.


        :param weight: The weight of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._weight = weight

    @property
    def quantity(self):
        """Gets the quantity of this ProductOptionItem.  # noqa: E501


        :return: The quantity of this ProductOptionItem.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ProductOptionItem.


        :param quantity: The quantity of this ProductOptionItem.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def type_price(self):
        """Gets the type_price of this ProductOptionItem.  # noqa: E501


        :return: The type_price of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._type_price

    @type_price.setter
    def type_price(self, type_price):
        """Sets the type_price of this ProductOptionItem.


        :param type_price: The type_price of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._type_price = type_price

    @property
    def sku(self):
        """Gets the sku of this ProductOptionItem.  # noqa: E501


        :return: The sku of this ProductOptionItem.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this ProductOptionItem.


        :param sku: The sku of this ProductOptionItem.  # noqa: E501
        :type: str
        """

        self._sku = sku

    @property
    def additional_fields(self):
        """Gets the additional_fields of this ProductOptionItem.  # noqa: E501


        :return: The additional_fields of this ProductOptionItem.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this ProductOptionItem.


        :param additional_fields: The additional_fields of this ProductOptionItem.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this ProductOptionItem.  # noqa: E501


        :return: The custom_fields of this ProductOptionItem.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this ProductOptionItem.


        :param custom_fields: The custom_fields of this ProductOptionItem.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductOptionItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductOptionItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
