# coding: utf-8

"""
    Swagger API2Cart

    API2Cart  # noqa: E501

    OpenAPI spec version: 1.1
    Contact: contact@api2cart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TaxClass(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'avail': 'bool',
        'tax': 'float',
        'tax_type': 'int',
        'tax_rates': 'list[TaxClassRate]',
        'additional_fields': 'object',
        'custom_fields': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'avail': 'avail',
        'tax': 'tax',
        'tax_type': 'tax_type',
        'tax_rates': 'tax_rates',
        'additional_fields': 'additional_fields',
        'custom_fields': 'custom_fields'
    }

    def __init__(self, id=None, name=None, avail=None, tax=None, tax_type=None, tax_rates=None, additional_fields=None, custom_fields=None):  # noqa: E501
        """TaxClass - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._avail = None
        self._tax = None
        self._tax_type = None
        self._tax_rates = None
        self._additional_fields = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if avail is not None:
            self.avail = avail
        if tax is not None:
            self.tax = tax
        if tax_type is not None:
            self.tax_type = tax_type
        if tax_rates is not None:
            self.tax_rates = tax_rates
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this TaxClass.  # noqa: E501


        :return: The id of this TaxClass.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TaxClass.


        :param id: The id of this TaxClass.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TaxClass.  # noqa: E501


        :return: The name of this TaxClass.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TaxClass.


        :param name: The name of this TaxClass.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def avail(self):
        """Gets the avail of this TaxClass.  # noqa: E501


        :return: The avail of this TaxClass.  # noqa: E501
        :rtype: bool
        """
        return self._avail

    @avail.setter
    def avail(self, avail):
        """Sets the avail of this TaxClass.


        :param avail: The avail of this TaxClass.  # noqa: E501
        :type: bool
        """

        self._avail = avail

    @property
    def tax(self):
        """Gets the tax of this TaxClass.  # noqa: E501


        :return: The tax of this TaxClass.  # noqa: E501
        :rtype: float
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """Sets the tax of this TaxClass.


        :param tax: The tax of this TaxClass.  # noqa: E501
        :type: float
        """

        self._tax = tax

    @property
    def tax_type(self):
        """Gets the tax_type of this TaxClass.  # noqa: E501


        :return: The tax_type of this TaxClass.  # noqa: E501
        :rtype: int
        """
        return self._tax_type

    @tax_type.setter
    def tax_type(self, tax_type):
        """Sets the tax_type of this TaxClass.


        :param tax_type: The tax_type of this TaxClass.  # noqa: E501
        :type: int
        """

        self._tax_type = tax_type

    @property
    def tax_rates(self):
        """Gets the tax_rates of this TaxClass.  # noqa: E501


        :return: The tax_rates of this TaxClass.  # noqa: E501
        :rtype: list[TaxClassRate]
        """
        return self._tax_rates

    @tax_rates.setter
    def tax_rates(self, tax_rates):
        """Sets the tax_rates of this TaxClass.


        :param tax_rates: The tax_rates of this TaxClass.  # noqa: E501
        :type: list[TaxClassRate]
        """

        self._tax_rates = tax_rates

    @property
    def additional_fields(self):
        """Gets the additional_fields of this TaxClass.  # noqa: E501


        :return: The additional_fields of this TaxClass.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this TaxClass.


        :param additional_fields: The additional_fields of this TaxClass.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this TaxClass.  # noqa: E501


        :return: The custom_fields of this TaxClass.  # noqa: E501
        :rtype: object
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this TaxClass.


        :param custom_fields: The custom_fields of this TaxClass.  # noqa: E501
        :type: object
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaxClass, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaxClass):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
